//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Members.EF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberLog
    {
        public int MemberLogId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> Accompany { get; set; }
        public string AccompanyName { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public Nullable<int> ModifiedByUserId { get; set; }
        public int Locked { get; set; }
        public int Visible { get; set; }
        public int Version { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
