//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 3.12.2015. 1:46:58
namespace PushSender.Service.Members.EF.Model
{
    /// <summary>
    /// There are no comments for MemberSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MemberSingle")]
    public partial class MemberSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Member>
    {
        /// <summary>
        /// Initialize a new MemberSingle object.
        /// </summary>
        public MemberSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MemberSingle object.
        /// </summary>
        public MemberSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MemberSingle object.
        /// </summary>
        public MemberSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Member> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for MemberLog in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLog")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.MemberLog> MemberLog
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._MemberLog == null))
                {
                    this._MemberLog = Context.CreateQuery<global::PushSender.Service.Members.EF.Model.MemberLog>(GetPath("MemberLog"));
                }
                return this._MemberLog;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.MemberLog> _MemberLog;
    }
    /// <summary>
    /// There are no comments for Member in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MemberId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("MemberId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
    public partial class Member : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="memberId">Initial value of MemberId.</param>
        /// <param name="locked">Initial value of Locked.</param>
        /// <param name="visible">Initial value of Visible.</param>
        /// <param name="version">Initial value of Version.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Member CreateMember(int memberId, bool locked, bool visible, int version)
        {
            Member member = new Member();
            member.MemberId = memberId;
            member.Locked = locked;
            member.Visible = visible;
            member.Version = version;
            return member;
        }
        /// <summary>
        /// There are no comments for Property MemberId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberId")]
        public int MemberId
        {
            get
            {
                return this._MemberId;
            }
            set
            {
                this.OnMemberIdChanging(value);
                this._MemberId = value;
                this.OnMemberIdChanged();
                this.OnPropertyChanged("MemberId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _MemberId;
        partial void OnMemberIdChanging(int value);
        partial void OnMemberIdChanged();
        /// <summary>
        /// There are no comments for Property MemberNo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberNo")]
        public global::System.Nullable<int> MemberNo
        {
            get
            {
                return this._MemberNo;
            }
            set
            {
                this.OnMemberNoChanging(value);
                this._MemberNo = value;
                this.OnMemberNoChanged();
                this.OnPropertyChanged("MemberNo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _MemberNo;
        partial void OnMemberNoChanging(global::System.Nullable<int> value);
        partial void OnMemberNoChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property BirthDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("BirthDate")]
        public global::System.Nullable<global::System.DateTimeOffset> BirthDate
        {
            get
            {
                return this._BirthDate;
            }
            set
            {
                this.OnBirthDateChanging(value);
                this._BirthDate = value;
                this.OnBirthDateChanged();
                this.OnPropertyChanged("BirthDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _BirthDate;
        partial void OnBirthDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnBirthDateChanged();
        /// <summary>
        /// There are no comments for Property Street in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Street")]
        public string Street
        {
            get
            {
                return this._Street;
            }
            set
            {
                this.OnStreetChanging(value);
                this._Street = value;
                this.OnStreetChanged();
                this.OnPropertyChanged("Street");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Street;
        partial void OnStreetChanging(string value);
        partial void OnStreetChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("City")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property PB in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PB")]
        public string PB
        {
            get
            {
                return this._PB;
            }
            set
            {
                this.OnPBChanging(value);
                this._PB = value;
                this.OnPBChanged();
                this.OnPropertyChanged("PB");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _PB;
        partial void OnPBChanging(string value);
        partial void OnPBChanged();
        /// <summary>
        /// There are no comments for Property OIB in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("OIB")]
        public string OIB
        {
            get
            {
                return this._OIB;
            }
            set
            {
                this.OnOIBChanging(value);
                this._OIB = value;
                this.OnOIBChanged();
                this.OnPropertyChanged("OIB");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _OIB;
        partial void OnOIBChanging(string value);
        partial void OnOIBChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property Phone in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Phone")]
        public string Phone
        {
            get
            {
                return this._Phone;
            }
            set
            {
                this.OnPhoneChanging(value);
                this._Phone = value;
                this.OnPhoneChanged();
                this.OnPropertyChanged("Phone");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Phone;
        partial void OnPhoneChanging(string value);
        partial void OnPhoneChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Gender")]
        public string Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Gender;
        partial void OnGenderChanging(string value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property CreatedByUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedByUserId")]
        public global::System.Nullable<int> CreatedByUserId
        {
            get
            {
                return this._CreatedByUserId;
            }
            set
            {
                this.OnCreatedByUserIdChanging(value);
                this._CreatedByUserId = value;
                this.OnCreatedByUserIdChanged();
                this.OnPropertyChanged("CreatedByUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _CreatedByUserId;
        partial void OnCreatedByUserIdChanging(global::System.Nullable<int> value);
        partial void OnCreatedByUserIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedByUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedByUserId")]
        public global::System.Nullable<int> ModifiedByUserId
        {
            get
            {
                return this._ModifiedByUserId;
            }
            set
            {
                this.OnModifiedByUserIdChanging(value);
                this._ModifiedByUserId = value;
                this.OnModifiedByUserIdChanged();
                this.OnPropertyChanged("ModifiedByUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ModifiedByUserId;
        partial void OnModifiedByUserIdChanging(global::System.Nullable<int> value);
        partial void OnModifiedByUserIdChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedDate")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedDate;
        partial void OnCreatedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedDate")]
        public global::System.Nullable<global::System.DateTimeOffset> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property Locked in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Locked")]
        public bool Locked
        {
            get
            {
                return this._Locked;
            }
            set
            {
                this.OnLockedChanging(value);
                this._Locked = value;
                this.OnLockedChanged();
                this.OnPropertyChanged("Locked");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _Locked;
        partial void OnLockedChanging(bool value);
        partial void OnLockedChanged();
        /// <summary>
        /// There are no comments for Property Visible in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Visible")]
        public bool Visible
        {
            get
            {
                return this._Visible;
            }
            set
            {
                this.OnVisibleChanging(value);
                this._Visible = value;
                this.OnVisibleChanged();
                this.OnPropertyChanged("Visible");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private bool _Visible;
        partial void OnVisibleChanging(bool value);
        partial void OnVisibleChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Version")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Country in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Country")]
        public string Country
        {
            get
            {
                return this._Country;
            }
            set
            {
                this.OnCountryChanging(value);
                this._Country = value;
                this.OnCountryChanged();
                this.OnPropertyChanged("Country");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _Country;
        partial void OnCountryChanging(string value);
        partial void OnCountryChanged();
        /// <summary>
        /// There are no comments for Property MemberLog in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLog")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::PushSender.Service.Members.EF.Model.MemberLog> MemberLog
        {
            get
            {
                return this._MemberLog;
            }
            set
            {
                this.OnMemberLogChanging(value);
                this._MemberLog = value;
                this.OnMemberLogChanged();
                this.OnPropertyChanged("MemberLog");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::PushSender.Service.Members.EF.Model.MemberLog> _MemberLog = new global::Microsoft.OData.Client.DataServiceCollection<global::PushSender.Service.Members.EF.Model.MemberLog>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnMemberLogChanging(global::Microsoft.OData.Client.DataServiceCollection<global::PushSender.Service.Members.EF.Model.MemberLog> value);
        partial void OnMemberLogChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DeviceSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceSingle")]
    public partial class DeviceSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Device>
    {
        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DeviceSingle object.
        /// </summary>
        public DeviceSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Device> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Device in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DeviceId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("DeviceId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Device")]
    public partial class Device : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Device object.
        /// </summary>
        /// <param name="deviceId">Initial value of DeviceId.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Device CreateDevice(int deviceId)
        {
            Device device = new Device();
            device.DeviceId = deviceId;
            return device;
        }
        /// <summary>
        /// There are no comments for Property DeviceId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceId")]
        public int DeviceId
        {
            get
            {
                return this._DeviceId;
            }
            set
            {
                this.OnDeviceIdChanging(value);
                this._DeviceId = value;
                this.OnDeviceIdChanged();
                this.OnPropertyChanged("DeviceId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _DeviceId;
        partial void OnDeviceIdChanging(int value);
        partial void OnDeviceIdChanged();
        /// <summary>
        /// There are no comments for Property DeviceUUID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceUUID")]
        public string DeviceUUID
        {
            get
            {
                return this._DeviceUUID;
            }
            set
            {
                this.OnDeviceUUIDChanging(value);
                this._DeviceUUID = value;
                this.OnDeviceUUIDChanged();
                this.OnPropertyChanged("DeviceUUID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _DeviceUUID;
        partial void OnDeviceUUIDChanging(string value);
        partial void OnDeviceUUIDChanged();
        /// <summary>
        /// There are no comments for Property PushToken in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("PushToken")]
        public string PushToken
        {
            get
            {
                return this._PushToken;
            }
            set
            {
                this.OnPushTokenChanging(value);
                this._PushToken = value;
                this.OnPushTokenChanged();
                this.OnPropertyChanged("PushToken");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _PushToken;
        partial void OnPushTokenChanging(string value);
        partial void OnPushTokenChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateCreated")]
        public global::System.Nullable<global::System.DateTimeOffset> DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this._DateCreated = value;
                this.OnDateCreatedChanged();
                this.OnPropertyChanged("DateCreated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateCreated;
        partial void OnDateCreatedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModifed in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateModifed")]
        public global::System.Nullable<global::System.DateTimeOffset> DateModifed
        {
            get
            {
                return this._DateModifed;
            }
            set
            {
                this.OnDateModifedChanging(value);
                this._DateModifed = value;
                this.OnDateModifedChanged();
                this.OnPropertyChanged("DateModifed");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _DateModifed;
        partial void OnDateModifedChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnDateModifedChanged();
        /// <summary>
        /// There are no comments for Property DeviceName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DeviceName")]
        public string DeviceName
        {
            get
            {
                return this._DeviceName;
            }
            set
            {
                this.OnDeviceNameChanging(value);
                this._DeviceName = value;
                this.OnDeviceNameChanged();
                this.OnPropertyChanged("DeviceName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _DeviceName;
        partial void OnDeviceNameChanging(string value);
        partial void OnDeviceNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for MemberLogSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLogSingle")]
    public partial class MemberLogSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<MemberLog>
    {
        /// <summary>
        /// Initialize a new MemberLogSingle object.
        /// </summary>
        public MemberLogSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new MemberLogSingle object.
        /// </summary>
        public MemberLogSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new MemberLogSingle object.
        /// </summary>
        public MemberLogSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<MemberLog> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public global::PushSender.Service.Members.EF.Model.MemberSingle Member
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Member == null))
                {
                    this._Member = new global::PushSender.Service.Members.EF.Model.MemberSingle(this.Context, GetPath("Member"));
                }
                return this._Member;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::PushSender.Service.Members.EF.Model.MemberSingle _Member;
    }
    /// <summary>
    /// There are no comments for MemberLog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MemberLogId
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("MemberLogId")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLog")]
    public partial class MemberLog : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MemberLog object.
        /// </summary>
        /// <param name="memberLogId">Initial value of MemberLogId.</param>
        /// <param name="locked">Initial value of Locked.</param>
        /// <param name="visible">Initial value of Visible.</param>
        /// <param name="version">Initial value of Version.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static MemberLog CreateMemberLog(int memberLogId, int locked, int visible, int version)
        {
            MemberLog memberLog = new MemberLog();
            memberLog.MemberLogId = memberLogId;
            memberLog.Locked = locked;
            memberLog.Visible = visible;
            memberLog.Version = version;
            return memberLog;
        }
        /// <summary>
        /// There are no comments for Property MemberLogId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberLogId")]
        public int MemberLogId
        {
            get
            {
                return this._MemberLogId;
            }
            set
            {
                this.OnMemberLogIdChanging(value);
                this._MemberLogId = value;
                this.OnMemberLogIdChanged();
                this.OnPropertyChanged("MemberLogId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _MemberLogId;
        partial void OnMemberLogIdChanging(int value);
        partial void OnMemberLogIdChanged();
        /// <summary>
        /// There are no comments for Property MemberId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("MemberId")]
        public global::System.Nullable<int> MemberId
        {
            get
            {
                return this._MemberId;
            }
            set
            {
                this.OnMemberIdChanging(value);
                this._MemberId = value;
                this.OnMemberIdChanged();
                this.OnPropertyChanged("MemberId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _MemberId;
        partial void OnMemberIdChanging(global::System.Nullable<int> value);
        partial void OnMemberIdChanged();
        /// <summary>
        /// There are no comments for Property LogDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LogDate")]
        public global::System.Nullable<global::System.DateTimeOffset> LogDate
        {
            get
            {
                return this._LogDate;
            }
            set
            {
                this.OnLogDateChanging(value);
                this._LogDate = value;
                this.OnLogDateChanged();
                this.OnPropertyChanged("LogDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LogDate;
        partial void OnLogDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLogDateChanged();
        /// <summary>
        /// There are no comments for Property Accompany in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Accompany")]
        public global::System.Nullable<int> Accompany
        {
            get
            {
                return this._Accompany;
            }
            set
            {
                this.OnAccompanyChanging(value);
                this._Accompany = value;
                this.OnAccompanyChanged();
                this.OnPropertyChanged("Accompany");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _Accompany;
        partial void OnAccompanyChanging(global::System.Nullable<int> value);
        partial void OnAccompanyChanged();
        /// <summary>
        /// There are no comments for Property AccompanyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AccompanyName")]
        public string AccompanyName
        {
            get
            {
                return this._AccompanyName;
            }
            set
            {
                this.OnAccompanyNameChanging(value);
                this._AccompanyName = value;
                this.OnAccompanyNameChanged();
                this.OnPropertyChanged("AccompanyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _AccompanyName;
        partial void OnAccompanyNameChanging(string value);
        partial void OnAccompanyNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedByUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedByUserId")]
        public global::System.Nullable<int> CreatedByUserId
        {
            get
            {
                return this._CreatedByUserId;
            }
            set
            {
                this.OnCreatedByUserIdChanging(value);
                this._CreatedByUserId = value;
                this.OnCreatedByUserIdChanged();
                this.OnPropertyChanged("CreatedByUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _CreatedByUserId;
        partial void OnCreatedByUserIdChanging(global::System.Nullable<int> value);
        partial void OnCreatedByUserIdChanged();
        /// <summary>
        /// There are no comments for Property ModifiedByUserId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedByUserId")]
        public global::System.Nullable<int> ModifiedByUserId
        {
            get
            {
                return this._ModifiedByUserId;
            }
            set
            {
                this.OnModifiedByUserIdChanging(value);
                this._ModifiedByUserId = value;
                this.OnModifiedByUserIdChanged();
                this.OnPropertyChanged("ModifiedByUserId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _ModifiedByUserId;
        partial void OnModifiedByUserIdChanging(global::System.Nullable<int> value);
        partial void OnModifiedByUserIdChanged();
        /// <summary>
        /// There are no comments for Property Locked in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Locked")]
        public int Locked
        {
            get
            {
                return this._Locked;
            }
            set
            {
                this.OnLockedChanging(value);
                this._Locked = value;
                this.OnLockedChanged();
                this.OnPropertyChanged("Locked");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Locked;
        partial void OnLockedChanging(int value);
        partial void OnLockedChanged();
        /// <summary>
        /// There are no comments for Property Visible in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Visible")]
        public int Visible
        {
            get
            {
                return this._Visible;
            }
            set
            {
                this.OnVisibleChanging(value);
                this._Visible = value;
                this.OnVisibleChanged();
                this.OnPropertyChanged("Visible");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Visible;
        partial void OnVisibleChanging(int value);
        partial void OnVisibleChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Version")]
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private int _Version;
        partial void OnVersionChanging(int value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property CreatedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreatedDate")]
        public global::System.Nullable<global::System.DateTimeOffset> CreatedDate
        {
            get
            {
                return this._CreatedDate;
            }
            set
            {
                this.OnCreatedDateChanging(value);
                this._CreatedDate = value;
                this.OnCreatedDateChanged();
                this.OnPropertyChanged("CreatedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _CreatedDate;
        partial void OnCreatedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnCreatedDateChanged();
        /// <summary>
        /// There are no comments for Property ModifiedDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ModifiedDate")]
        public global::System.Nullable<global::System.DateTimeOffset> ModifiedDate
        {
            get
            {
                return this._ModifiedDate;
            }
            set
            {
                this.OnModifiedDateChanging(value);
                this._ModifiedDate = value;
                this.OnModifiedDateChanged();
                this.OnPropertyChanged("ModifiedDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _ModifiedDate;
        partial void OnModifiedDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnModifiedDateChanged();
        /// <summary>
        /// There are no comments for Property Member in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Member")]
        public global::PushSender.Service.Members.EF.Model.Member Member
        {
            get
            {
                return this._Member;
            }
            set
            {
                this.OnMemberChanging(value);
                this._Member = value;
                this.OnMemberChanged();
                this.OnPropertyChanged("Member");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::PushSender.Service.Members.EF.Model.Member _Member;
        partial void OnMemberChanging(global::PushSender.Service.Members.EF.Model.Member value);
        partial void OnMemberChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::PushSender.Service.Members.EF.Model.Member as global::PushSender.Service.Members.EF.Model.MemberSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::PushSender.Service.Members.EF.Model.MemberSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Member> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::PushSender.Service.Members.EF.Model.MemberSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PushSender.Service.Members.EF.Model.Member as global::PushSender.Service.Members.EF.Model.MemberSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="memberId">The value of memberId</param>
        public static global::PushSender.Service.Members.EF.Model.MemberSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Member> source,
            int memberId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "MemberId", memberId }
            };
            return new global::PushSender.Service.Members.EF.Model.MemberSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PushSender.Service.Members.EF.Model.Device as global::PushSender.Service.Members.EF.Model.DeviceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::PushSender.Service.Members.EF.Model.DeviceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Device> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::PushSender.Service.Members.EF.Model.DeviceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PushSender.Service.Members.EF.Model.Device as global::PushSender.Service.Members.EF.Model.DeviceSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="deviceId">The value of deviceId</param>
        public static global::PushSender.Service.Members.EF.Model.DeviceSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Device> source,
            int deviceId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "DeviceId", deviceId }
            };
            return new global::PushSender.Service.Members.EF.Model.DeviceSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PushSender.Service.Members.EF.Model.MemberLog as global::PushSender.Service.Members.EF.Model.MemberLogSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::PushSender.Service.Members.EF.Model.MemberLogSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.MemberLog> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::PushSender.Service.Members.EF.Model.MemberLogSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::PushSender.Service.Members.EF.Model.MemberLog as global::PushSender.Service.Members.EF.Model.MemberLogSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="memberLogId">The value of memberLogId</param>
        public static global::PushSender.Service.Members.EF.Model.MemberLogSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.MemberLog> source,
            int memberLogId)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "MemberLogId", memberLogId }
            };
            return new global::PushSender.Service.Members.EF.Model.MemberLogSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace PushSender.Service.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Members.EF.Model", "PushSender.Service.Members.EF.Model");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "PushSender.Service.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("PushSender.Service.Members.EF.Model", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Members.EF.Model.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Members.EF.Model.", clientType.Name);
            }
            if (clientType.Namespace.Equals("PushSender.Service.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Members in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Members")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Member> Members
        {
            get
            {
                if ((this._Members == null))
                {
                    this._Members = base.CreateQuery<global::PushSender.Service.Members.EF.Model.Member>("Members");
                }
                return this._Members;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Member> _Members;
        /// <summary>
        /// There are no comments for Device in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Device")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Device> Device
        {
            get
            {
                if ((this._Device == null))
                {
                    this._Device = base.CreateQuery<global::PushSender.Service.Members.EF.Model.Device>("Device");
                }
                return this._Device;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::PushSender.Service.Members.EF.Model.Device> _Device;
        /// <summary>
        /// There are no comments for Members in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToMembers(global::PushSender.Service.Members.EF.Model.Member member)
        {
            base.AddObject("Members", member);
        }
        /// <summary>
        /// There are no comments for Device in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToDevice(global::PushSender.Service.Members.EF.Model.Device device)
        {
            base.AddObject("Device", device);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Members.EF.Model"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Member"">
        <Key>
          <PropertyRef Name=""MemberId"" />
        </Key>
        <Property Name=""MemberId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MemberNo"" Type=""Edm.Int32"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""BirthDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Street"" Type=""Edm.String"" />
        <Property Name=""City"" Type=""Edm.String"" />
        <Property Name=""PB"" Type=""Edm.String"" />
        <Property Name=""OIB"" Type=""Edm.String"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""Phone"" Type=""Edm.String"" />
        <Property Name=""Gender"" Type=""Edm.String"" />
        <Property Name=""CreatedByUserId"" Type=""Edm.Int32"" />
        <Property Name=""ModifiedByUserId"" Type=""Edm.Int32"" />
        <Property Name=""CreatedDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ModifiedDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Locked"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""Visible"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""Version"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Country"" Type=""Edm.String"" />
        <NavigationProperty Name=""MemberLog"" Type=""Collection(Members.EF.Model.MemberLog)"" />
      </EntityType>
      <EntityType Name=""Device"">
        <Key>
          <PropertyRef Name=""DeviceId"" />
        </Key>
        <Property Name=""DeviceId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""DeviceUUID"" Type=""Edm.String"" />
        <Property Name=""PushToken"" Type=""Edm.String"" />
        <Property Name=""DateCreated"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DateModifed"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""DeviceName"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""MemberLog"">
        <Key>
          <PropertyRef Name=""MemberLogId"" />
        </Key>
        <Property Name=""MemberLogId"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""MemberId"" Type=""Edm.Int32"" />
        <Property Name=""LogDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""Accompany"" Type=""Edm.Int32"" />
        <Property Name=""AccompanyName"" Type=""Edm.String"" />
        <Property Name=""CreatedByUserId"" Type=""Edm.Int32"" />
        <Property Name=""ModifiedByUserId"" Type=""Edm.Int32"" />
        <Property Name=""Locked"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Visible"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Version"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""CreatedDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""ModifiedDate"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""Member"" Type=""Members.EF.Model.Member"">
          <ReferentialConstraint Property=""MemberId"" ReferencedProperty=""MemberId"" />
        </NavigationProperty>
      </EntityType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Members"" EntityType=""Members.EF.Model.Member"" />
        <EntitySet Name=""Device"" EntityType=""Members.EF.Model.Device"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
